extract = 'total_dyn_inst: (\d+)'
benchmarks = './benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "python my_lvn.py",
    "python my_trivial_dce.py",
    "brili -p {args}",
]
